{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.2.27/toolkit-store-0.2.27.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.2.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.27"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-release.aar",
          "url": "toolkit-store-android-0.2.27.aar",
          "size": 59679,
          "sha512": "094bb8fe7b03869b04cea1b1030520c2cf63d6c835c416cc3354dd97bd4d0e729cb67520823642723aae71dc6cb9c7d1e70621eec0f767d9382fee474c18cfd1",
          "sha256": "341592132276bd099e978aca8605c5f605a10a089cdba60c303e859ab239f06f",
          "sha1": "345657923502da1b5278ee8c775fd01dd6aa45ec",
          "md5": "fe87d102519184d8516cc1d76a27c559"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.27"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "toolkit-store-release.aar",
          "url": "toolkit-store-android-0.2.27.aar",
          "size": 59679,
          "sha512": "094bb8fe7b03869b04cea1b1030520c2cf63d6c835c416cc3354dd97bd4d0e729cb67520823642723aae71dc6cb9c7d1e70621eec0f767d9382fee474c18cfd1",
          "sha256": "341592132276bd099e978aca8605c5f605a10a089cdba60c303e859ab239f06f",
          "sha1": "345657923502da1b5278ee8c775fd01dd6aa45ec",
          "md5": "fe87d102519184d8516cc1d76a27c559"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "toolkit-store-android-0.2.27-sources.jar",
          "url": "toolkit-store-android-0.2.27-sources.jar",
          "size": 20025,
          "sha512": "48daf25263dd6d9eb94f10159c836025ca1550485dc419d96441f17696f7cad92e5085fef7722d3e7150d3da64eefa423b24af2273c5729f4d201832fcf5adc2",
          "sha256": "dad12be15092553e0feb01ed525a7a4af7aeb6b1a6c74ed1dcf8057aa75a32a9",
          "sha1": "a54a2ff89a6baeb68559b032754b7f9de818885d",
          "md5": "6cdbd325ea10b81c01132744f503649c"
        }
      ]
    }
  ]
}
