{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-compose/0.2.26/toolkit-compose-0.2.26.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-compose",
    "version": "0.2.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.26"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-compose-release.aar",
          "url": "toolkit-compose-android-0.2.26.aar",
          "size": 30035,
          "sha512": "fce7be969abe7bfa25799c869b098793eab01b2be666f241793e2352502c83bb349edd3b7f91a855970b3ae171ec043f765a2e388b81a882e22f08430f5c1f9b",
          "sha256": "dc33634610547b4c1d9ab25efea361cfbaeebf18b234b447159bf681a87d58c7",
          "sha1": "c7e6f031923ba79cad71c7d6b070deaabfc05e83",
          "md5": "c86195f5ee2c70da77d41e4fdb72ef2e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.26"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "toolkit-compose-release.aar",
          "url": "toolkit-compose-android-0.2.26.aar",
          "size": 30035,
          "sha512": "fce7be969abe7bfa25799c869b098793eab01b2be666f241793e2352502c83bb349edd3b7f91a855970b3ae171ec043f765a2e388b81a882e22f08430f5c1f9b",
          "sha256": "dc33634610547b4c1d9ab25efea361cfbaeebf18b234b447159bf681a87d58c7",
          "sha1": "c7e6f031923ba79cad71c7d6b070deaabfc05e83",
          "md5": "c86195f5ee2c70da77d41e4fdb72ef2e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "toolkit-compose-android-0.2.26-sources.jar",
          "url": "toolkit-compose-android-0.2.26-sources.jar",
          "size": 5238,
          "sha512": "d4da4ed92db69c392e2e32cbe21ab2d882f667b33553129a4695489d255104814e8d054dc143db38792d7e41fa43ab09efdfffcbb324e8fb134a7afb79297954",
          "sha256": "e07f32c0cb95863ee4c1111a6a6d7b07c29b17de180b1dbd34bd8d7df1e76260",
          "sha1": "8d52ebfaf4738574f67d0f106a9a8c5aae5049dc",
          "md5": "0043615e43dc74c01b372a6190d96d5e"
        }
      ]
    }
  ]
}
