{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.1.0/toolkit-store-0.1.0.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-jvm-0.1.0.jar",
          "url": "toolkit-store-jvm-0.1.0.jar",
          "size": 8992,
          "sha512": "12ab59a28a647007e0483ed732a0897c5f3a1ec2120534b81f53498c18aa28fce6b93bc8194cadaf1aa820d98c843271148775ed81b7a4f4d67d8fa8eac01f97",
          "sha256": "1e53788df04691f6745490f5668bcd124c67592c990c2047374b853acde4405f",
          "sha1": "9c0ca8d8701b9e831c1232943334cf0cb1f51417",
          "md5": "da927e03307db2867e5e5802729e47cf"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-jvm-0.1.0.jar",
          "url": "toolkit-store-jvm-0.1.0.jar",
          "size": 8992,
          "sha512": "12ab59a28a647007e0483ed732a0897c5f3a1ec2120534b81f53498c18aa28fce6b93bc8194cadaf1aa820d98c843271148775ed81b7a4f4d67d8fa8eac01f97",
          "sha256": "1e53788df04691f6745490f5668bcd124c67592c990c2047374b853acde4405f",
          "sha1": "9c0ca8d8701b9e831c1232943334cf0cb1f51417",
          "md5": "da927e03307db2867e5e5802729e47cf"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "toolkit-store-jvm-0.1.0-sources.jar",
          "url": "toolkit-store-jvm-0.1.0-sources.jar",
          "size": 8647,
          "sha512": "d498cee512a6b6e08eb09216814d423fbd84657d252b56a0f45bbefeca277a4b1aafb3b98a3e46c893a9a157666fe8c770ba90a61cc048d5731325a74c25850e",
          "sha256": "99abe8b0ac7f5baa7bfed09abc5428a731e28ac76bab080733d42095367b0b4e",
          "sha1": "f691b1228ed9860335da57866841b88072d35b2a",
          "md5": "c545c1f9f7428e9b80b17ed690088eb7"
        }
      ]
    }
  ]
}
