{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.2.13/toolkit-store-0.2.13.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.2.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-js-0.2.13.klib",
          "url": "toolkit-store-js-0.2.13.klib",
          "size": 40525,
          "sha512": "23d68dfcea37d21e86d81efb91bfd46e5bd439380fa08ebb3a9a9801f2b7d386ede49301b916a64849117875926486ac4620971ab8fc40152cebbda6d536cb8f",
          "sha256": "91580d494657e591e2faa7da958d1cbe3a61e01c736173935bd4e696ce6641ae",
          "sha1": "92cefdf2942dce3fe8f00cebd0bffc14ccce0a4a",
          "md5": "65aac27134d55199fddae360b1da1410"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-js-0.2.13.klib",
          "url": "toolkit-store-js-0.2.13.klib",
          "size": 40525,
          "sha512": "23d68dfcea37d21e86d81efb91bfd46e5bd439380fa08ebb3a9a9801f2b7d386ede49301b916a64849117875926486ac4620971ab8fc40152cebbda6d536cb8f",
          "sha256": "91580d494657e591e2faa7da958d1cbe3a61e01c736173935bd4e696ce6641ae",
          "sha1": "92cefdf2942dce3fe8f00cebd0bffc14ccce0a4a",
          "md5": "65aac27134d55199fddae360b1da1410"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-store-js-0.2.13-sources.jar",
          "url": "toolkit-store-js-0.2.13-sources.jar",
          "size": 13475,
          "sha512": "87ca897907fbb9f526ddd9818e28044b9701854327f7a7987563f09f8f3860db9b92c9dc63277893cecb1f57d57a507c49dda9fcba4e4a8a7bfbadd3f2c5785d",
          "sha256": "dbb97c35372a2f1d158ad6fc5f49d0b089ba6a52ed27a673253edd8147f4aefa",
          "sha1": "9241dc3c2d02d01f07c150edf500859afe60d0d9",
          "md5": "2a1c60624b156c748e3fde203f476720"
        }
      ]
    }
  ]
}
