{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-web/0.2.27/toolkit-web-0.2.27.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-web",
    "version": "0.2.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.27"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.27.klib",
          "url": "toolkit-web-js-0.2.27.klib",
          "size": 770089,
          "sha512": "f9076be7951710927f61558649a04f23a470813d4ad1ac30f9c7bcb6db67ae39566f851515edf93a1b95122c56a2d82ba4e5c9bd82781f935291f236d2a853ae",
          "sha256": "8bb26a34758fefb31b71f9625767f7340fcce25706620038b7b286c24c9f2510",
          "sha1": "c9562a31db15a31b654520a0ac2567b1abbb1601",
          "md5": "ab5a47627086bce488fa021a05395fef"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.27"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.27.klib",
          "url": "toolkit-web-js-0.2.27.klib",
          "size": 770089,
          "sha512": "f9076be7951710927f61558649a04f23a470813d4ad1ac30f9c7bcb6db67ae39566f851515edf93a1b95122c56a2d82ba4e5c9bd82781f935291f236d2a853ae",
          "sha256": "8bb26a34758fefb31b71f9625767f7340fcce25706620038b7b286c24c9f2510",
          "sha1": "c9562a31db15a31b654520a0ac2567b1abbb1601",
          "md5": "ab5a47627086bce488fa021a05395fef"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-web-js-0.2.27-sources.jar",
          "url": "toolkit-web-js-0.2.27-sources.jar",
          "size": 330185,
          "sha512": "e64b6ffdc3ca40b7244b5eec031aa95f33455dc96ed917390aab8ca24c18c3965ee94e1012fed1d4686af6f14b4ef6f7bbfaec5f4bff572d867501605af1e132",
          "sha256": "d098fd3bde4808173078df1e1050220d129c920b2f686a441deb490add49aebe",
          "sha1": "0c31b94be7940653093243df20aa564e82141ecb",
          "md5": "8812f2d18387c847cde3537b3a2b9771"
        }
      ]
    }
  ]
}
