{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.19/toolkit-core-0.2.19.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-js-0.2.19.klib",
          "url": "toolkit-core-js-0.2.19.klib",
          "size": 106168,
          "sha512": "cdd8586573dadc293c22bae09c661ae3607f4b4ecb3038ac28a029e8756e72bfca75b5b9a17b129b28f9e869531cae6a70dcae1c910c5a4a9b9b3e027c2150b4",
          "sha256": "12d3ee0e5a21559c7714c867648af8051663689d294626adca19b08868f81a08",
          "sha1": "660fa482a4d94bb7e896ddfeb24f1e4202695888",
          "md5": "4a8075400bc40e04a67990fb201e8429"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-js-0.2.19.klib",
          "url": "toolkit-core-js-0.2.19.klib",
          "size": 106168,
          "sha512": "cdd8586573dadc293c22bae09c661ae3607f4b4ecb3038ac28a029e8756e72bfca75b5b9a17b129b28f9e869531cae6a70dcae1c910c5a4a9b9b3e027c2150b4",
          "sha256": "12d3ee0e5a21559c7714c867648af8051663689d294626adca19b08868f81a08",
          "sha1": "660fa482a4d94bb7e896ddfeb24f1e4202695888",
          "md5": "4a8075400bc40e04a67990fb201e8429"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-core-js-0.2.19-sources.jar",
          "url": "toolkit-core-js-0.2.19-sources.jar",
          "size": 36059,
          "sha512": "d49a2c50b6eae1c7695567ee1445f3bafa377ceb428cf2d3d439449233975d13652355dc533522f58e775aca80660c41b614f48df750f6e265108ef09299edba",
          "sha256": "c4b41f4cc0d92ff82cd0e18b6a8bf1f764b571a90209ae87efc870aed7c8d51d",
          "sha1": "2c939e18e294e625096665aeec7030f3afdf3d9a",
          "md5": "995a158411c76885d5751a848c00db71"
        }
      ]
    }
  ]
}
