{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.2.26/toolkit-store-0.2.26.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.2.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.26"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-jvm-0.2.26.jar",
          "url": "toolkit-store-jvm-0.2.26.jar",
          "size": 60735,
          "sha512": "c3629a24a3b6e517ca15a23079c7b624e12c1ef1da0f1237b8f3a217f3adb838a065e177c771e5b32d59b64525faab5c6e79a75b1061ac503be501dda7dffb1c",
          "sha256": "48c6e923f8dc8fa1e230eaf20e1db7b89429d808e9cfa0ed4a788b275a0799e8",
          "sha1": "5ad5349b220ff83184a76c90f26cd4195c6c375b",
          "md5": "70d565db79354c16328c2a2eba9303ef"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.26"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-jvm-0.2.26.jar",
          "url": "toolkit-store-jvm-0.2.26.jar",
          "size": 60735,
          "sha512": "c3629a24a3b6e517ca15a23079c7b624e12c1ef1da0f1237b8f3a217f3adb838a065e177c771e5b32d59b64525faab5c6e79a75b1061ac503be501dda7dffb1c",
          "sha256": "48c6e923f8dc8fa1e230eaf20e1db7b89429d808e9cfa0ed4a788b275a0799e8",
          "sha1": "5ad5349b220ff83184a76c90f26cd4195c6c375b",
          "md5": "70d565db79354c16328c2a2eba9303ef"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "toolkit-store-jvm-0.2.26-sources.jar",
          "url": "toolkit-store-jvm-0.2.26-sources.jar",
          "size": 21976,
          "sha512": "0db2b634f3c66782a69f0f74374e5bbb20d66a5bb73756eb331062a2a25ae3fac7de20c71144282b6023e213efc2d7fe392c7469dd838d9fea686fd105a3203c",
          "sha256": "5ef1c46f59f50efdad34d2428debc45d8c9a21be74c682c7627235d86932ac52",
          "sha1": "1f6765d0a9d2d9bcc7086e1877da22b1153b89fc",
          "md5": "ecb5bf4d10a04e30078de42b3a072857"
        }
      ]
    }
  ]
}
