/**
 * Built-in (default) [Theme] definitions for Termtastic.
 *
 * A [Theme] is a named snapshot of a main colour scheme plus per-section
 * overrides (sidebar, terminal, diff, file browser, tabs, chrome, windows,
 * and active indicators). The themes defined here ship with the app and
 * cannot be deleted by the user, though they can be reordered alongside
 * user-created themes.
 *
 * Each theme references colour schemes by name from [recommendedColorSchemes].
 * An empty string on a section override means "use the main colour scheme".
 *
 * @see recommendedColorSchemes
 * @see ColorScheme
 * @see se.soderbjorn.termtastic.client.UiSettings
 */
package se.soderbjorn.termtastic

/**
 * Which appearance mode(s) a built-in [Theme] is designed for.
 *
 * @see Theme.mode
 */
enum class ConfigMode {
    /** Optimised for dark appearance. */
    Dark,
    /** Optimised for light appearance. */
    Light,
    /** Works well in both dark and light appearance. */
    Both,
}

/**
 * A theme: a named composition that maps a main colour scheme plus optional
 * per-section colour-scheme overrides. Corresponds to what the UI calls a
 * "theme" (as distinct from a "colour scheme", which is a single palette).
 *
 * @property name         Human-readable theme name shown in the theme list.
 * @property mode         Which appearance mode(s) this theme is designed for.
 * @property colorScheme  Name of the main colour scheme (must exist in
 *   [recommendedColorSchemes]). Used as the default for any section whose
 *   own override is empty.
 * @property sidebar      Section override for the sidebar, or empty for default.
 * @property terminal     Section override for the terminal panes.
 * @property diff         Section override for the diff viewer.
 * @property fileBrowser  Section override for the file browser / markdown viewer.
 * @property tabs         Section override for the tab strip.
 * @property chrome       Section override for the window chrome / titlebar.
 * @property windows      Section override for the pane frames / borders.
 * @property active       Section override for focus rings and active indicators.
 *
 * @see ColorScheme
 * @see defaultThemes
 */
data class Theme(
    val name: String,
    val mode: ConfigMode = ConfigMode.Both,
    val colorScheme: String,
    val sidebar: String = "",
    val terminal: String = "",
    val diff: String = "",
    val fileBrowser: String = "",
    val tabs: String = "",
    val chrome: String = "",
    val windows: String = "",
    val active: String = "",
    val bottomBar: String = "",
)

/**
 * The list of built-in [Theme]s that ship with Termtastic.
 *
 * Each entry is a curated combination of colour schemes assigned to different
 * UI sections, designed to produce a cohesive and visually distinct look.
 * Users can reorder these alongside their custom themes, but cannot delete
 * them.
 *
 * @see Theme
 */
val defaultThemes: List<Theme> = listOf(
    // ── Dual-mode configurations ──────────────────────────────────────

    // Cohesive single-theme preset — same Verdant scheme across every
    // section, matching the uniform minimalist-IDE look in the source
    // screenshots (near-black green-tinted dark / cream paper light).
    // `active = "Verdant"` makes the accent/focus rings explicit so the
    // picker shows the mint green in the indicator preview.
    Theme(
        name = "Verdant",
        mode = ConfigMode.Both,
        colorScheme = "Verdant",
        sidebar = "Verdant",
        terminal = "Verdant",
        diff = "Verdant",
        fileBrowser = "Verdant",
        tabs = "Verdant",
        chrome = "Verdant",
        windows = "Verdant",
        active = "Verdant",
        bottomBar = "Verdant",
    ),

    // ── Dark mode configurations ──────────────────────────────────────

    Theme(
        name = "Neon Circuit",
        mode = ConfigMode.Dark,
        colorScheme = "Tron",
        sidebar = "Vapor pink",
        terminal = "Cyber teal",
        tabs = "Tron",
        active = "Plasma",
    ),
    Theme(
        name = "Sunset Drive",
        mode = ConfigMode.Dark,
        colorScheme = "Amber Glow",
        sidebar = "Ember",
        terminal = "Coral",
        tabs = "Sunset",
        active = "Sunset",
    ),
    Theme(
        name = "Purple Haze",
        mode = ConfigMode.Dark,
        colorScheme = "Dracula",
        sidebar = "Royal violet",
        terminal = "Ultraviolet",
        tabs = "Dracula",
        active = "Lavender",
    ),
    Theme(
        name = "Cyber Noir",
        mode = ConfigMode.Dark,
        colorScheme = "Night Owl",
        sidebar = "Tron",
        terminal = "Matrix",
        windows = "Ayu Mirage",
        tabs = "Night Owl",
        diff = "Ayu",
        active = "Cyber teal",
    ),
    Theme(
        name = "Ember Dusk",
        mode = ConfigMode.Dark,
        colorScheme = "One Dark",
        sidebar = "Monokai",
        terminal = "Lava",
        windows = "One Dark",
        tabs = "Hopscotch",
        diff = "Dracula",
        active = "Crimson",
    ),
    Theme(
        name = "Candy Pop",
        mode = ConfigMode.Dark,
        colorScheme = "Catppuccin",
        sidebar = "Dracula",
        terminal = "Vapor pink",
        windows = "Catppuccin",
        tabs = "Hopscotch",
        diff = "Rose Pine",
        active = "Magenta",
    ),
    Theme(
        name = "Ubuntu Terminal",
        mode = ConfigMode.Dark,
        colorScheme = "Ubuntu",
        sidebar = "Dracula",
        terminal = "Cherry",
        windows = "Hopscotch",
        tabs = "Ubuntu",
        diff = "One Dark",
        active = "Hot rose",
    ),
    Theme(
        name = "Hacker",
        mode = ConfigMode.Dark,
        colorScheme = "Ayu",
        sidebar = "Night Owl",
        terminal = "Matrix",
        windows = "Ayu",
        tabs = "Spacegray",
        diff = "Monokai",
        fileBrowser = "Ayu Mirage",
        active = "Cyber lime",
    ),
    Theme(
        name = "Retro Terminal",
        mode = ConfigMode.Dark,
        colorScheme = "Pencil",
        sidebar = "Ayu",
        terminal = "Amber CRT",
        windows = "Pencil",
        tabs = "Spacegray",
        diff = "Monokai",
        fileBrowser = "Pencil",
        active = "Cyber lime",
    ),

    Theme(
        name = "Magma",
        mode = ConfigMode.Dark,
        colorScheme = "Monokai",
        sidebar = "Hopscotch",
        terminal = "Crimson",
        windows = "Monokai",
        tabs = "Ubuntu",
        diff = "Dracula",
        active = "Lava",
    ),
    Theme(
        name = "Midnight Oil",
        mode = ConfigMode.Dark,
        colorScheme = "Ayu Mirage",
        sidebar = "Cobalt2",
        terminal = "Indigo",
        windows = "Ayu Mirage",
        tabs = "Night Owl",
        diff = "Tokyo Night",
        active = "Cobalt",
    ),
    Theme(
        name = "Toxic",
        mode = ConfigMode.Dark,
        colorScheme = "Matrix",
        sidebar = "Ayu",
        terminal = "Cyber lime",
        windows = "Spacegray",
        tabs = "Pencil",
        diff = "Monokai",
        active = "Aqua glow",
    ),
    Theme(
        name = "Outrun",
        mode = ConfigMode.Dark,
        colorScheme = "Synthwave",
        sidebar = "Dracula",
        terminal = "Hot rose",
        windows = "Catppuccin",
        tabs = "Hopscotch",
        diff = "Rose Pine",
        active = "Vapor pink",
    ),
    Theme(
        name = "Deep Space",
        mode = ConfigMode.Dark,
        colorScheme = "Night Owl",
        sidebar = "Tokyo Night",
        terminal = "Cobalt",
        windows = "Night Owl",
        tabs = "Ayu Mirage",
        diff = "Nord",
        active = "Periwinkle",
    ),
    Theme(
        name = "Molten Gold",
        mode = ConfigMode.Dark,
        colorScheme = "Sepia",
        sidebar = "Monokai",
        terminal = "Sunflower",
        windows = "Sepia",
        tabs = "Gruvbox",
        diff = "One Dark",
        active = "Honey",
    ),
    Theme(
        name = "Blood Moon",
        mode = ConfigMode.Dark,
        colorScheme = "Dracula",
        sidebar = "Ubuntu",
        terminal = "Cherry",
        windows = "Hopscotch",
        tabs = "Dracula",
        diff = "One Dark",
        active = "Crimson",
    ),

    // ── Light mode configurations ─────────────────────────────────────

    Theme(
        name = "Paper & Ink",
        mode = ConfigMode.Light,
        colorScheme = "Paper White",
        sidebar = "GitHub",
        terminal = "Pencil",
        windows = "Paper White",
        tabs = "Spacegray",
        diff = "GitHub",
        active = "Mono Black",
    ),
    Theme(
        name = "Solarized Warm",
        mode = ConfigMode.Light,
        colorScheme = "Solarized",
        sidebar = "Sepia",
        terminal = "Solarized",
        windows = "Gruvbox",
        tabs = "Sepia",
        diff = "Solarized",
        active = "Honey",
    ),
    Theme(
        name = "Morning Fog",
        mode = ConfigMode.Light,
        colorScheme = "Nord",
        sidebar = "Spacegray",
        terminal = "GitHub",
        windows = "Nord",
        tabs = "Material",
        diff = "Nord",
        active = "Sky",
    ),
    Theme(
        name = "Lavender Fields",
        mode = ConfigMode.Light,
        colorScheme = "Catppuccin",
        sidebar = "Rose Pine",
        terminal = "Lavender",
        windows = "Catppuccin",
        tabs = "Hopscotch",
        diff = "Rose Pine",
        active = "Royal violet",
    ),
    Theme(
        name = "Cream & Coffee",
        mode = ConfigMode.Light,
        colorScheme = "Gruvbox",
        sidebar = "Sepia",
        terminal = "Sand",
        windows = "Gruvbox",
        tabs = "Monokai",
        diff = "Gruvbox",
        fileBrowser = "Sepia",
        active = "Amber Glow",
    ),
    Theme(
        name = "Ocean Breeze",
        mode = ConfigMode.Light,
        colorScheme = "GitHub",
        sidebar = "Cobalt2",
        terminal = "Sky",
        windows = "GitHub",
        tabs = "Nord",
        diff = "Material",
        active = "Ocean",
    ),
    Theme(
        name = "Spring Garden",
        mode = ConfigMode.Light,
        colorScheme = "One Dark",
        sidebar = "Gruvbox",
        terminal = "Mint Cream",
        windows = "One Dark",
        tabs = "Material",
        diff = "GitHub",
        fileBrowser = "One Dark",
        active = "Sea Foam",
    ),
    Theme(
        name = "Peach Blossom",
        mode = ConfigMode.Light,
        colorScheme = "Rose Pine",
        sidebar = "Catppuccin",
        terminal = "Peach",
        windows = "Rose Pine",
        tabs = "Hopscotch",
        diff = "Catppuccin",
        active = "Coral",
    ),
    Theme(
        name = "Clean Slate",
        mode = ConfigMode.Light,
        colorScheme = "Mono Black",
        sidebar = "GitHub",
        terminal = "Spacegray",
        windows = "Pencil",
        tabs = "Mono Black",
        diff = "GitHub",
        active = "Cobalt",
    ),
    Theme(
        name = "Ubuntu Rose",
        mode = ConfigMode.Light,
        colorScheme = "Ubuntu",
        sidebar = "Hopscotch",
        terminal = "Pastel Pink",
        windows = "Ubuntu",
        tabs = "Rose Pine",
        diff = "Catppuccin",
        active = "Cherry",
    ),

    Theme(
        name = "Ivory Tower",
        mode = ConfigMode.Light,
        colorScheme = "GitHub",
        sidebar = "One Dark",
        terminal = "Paper White",
        windows = "GitHub",
        tabs = "Spacegray",
        diff = "Nord",
        active = "Indigo",
    ),
    Theme(
        name = "Mint Tea",
        mode = ConfigMode.Light,
        colorScheme = "Material",
        sidebar = "Nord",
        terminal = "Mint Cream",
        windows = "Material",
        tabs = "GitHub",
        diff = "One Dark",
        active = "Sea Foam",
    ),
    Theme(
        name = "Sunset Terrace",
        mode = ConfigMode.Light,
        colorScheme = "Gruvbox",
        sidebar = "Monokai",
        terminal = "Peach",
        windows = "Gruvbox",
        tabs = "Sepia",
        diff = "One Dark",
        fileBrowser = "Gruvbox",
        active = "Coral",
    ),
    Theme(
        name = "Nordic Frost",
        mode = ConfigMode.Light,
        colorScheme = "Nord",
        sidebar = "Cobalt2",
        terminal = "Ice",
        windows = "Nord",
        tabs = "GitHub",
        diff = "Material",
        active = "Periwinkle",
    ),
    Theme(
        name = "Daybreak",
        mode = ConfigMode.Light,
        colorScheme = "One Dark",
        sidebar = "Catppuccin",
        terminal = "Sky",
        windows = "One Dark",
        tabs = "Nord",
        diff = "GitHub",
        active = "Ocean",
    ),
    Theme(
        name = "Honey Bee",
        mode = ConfigMode.Light,
        colorScheme = "Sepia",
        sidebar = "Gruvbox",
        terminal = "Sunflower",
        windows = "Sepia",
        tabs = "Monokai",
        diff = "Gruvbox",
        active = "Amber Glow",
    ),

    // ── Both modes ────────────────────────────────────────────────────

    Theme(
        name = "Deep Ocean",
        colorScheme = "Nord",
        sidebar = "Cobalt",
        terminal = "Ocean",
        tabs = "Nord",
        active = "Ice",
    ),
    Theme(
        name = "Forest Floor",
        colorScheme = "Gruvbox",
        sidebar = "Forest",
        terminal = "Sage",
        tabs = "Gruvbox",
        active = "Olive",
    ),
    Theme(
        name = "Tokyo Midnight",
        colorScheme = "Tokyo Night",
        sidebar = "Dracula",
        terminal = "Catppuccin",
        tabs = "Tokyo Night",
        active = "Rose Pine",
    ),
    Theme(
        name = "Solarized Classic",
        colorScheme = "Solarized",
    ),
    Theme(
        name = "Warm Hearth",
        colorScheme = "Monokai",
        sidebar = "Sepia",
        terminal = "Amber CRT",
        tabs = "Monokai",
        active = "Honey",
    ),
    Theme(
        name = "Rose Garden",
        colorScheme = "Rose Pine",
        sidebar = "Catppuccin",
        terminal = "Pastel Pink",
        tabs = "Rose Pine",
        active = "Hopscotch",
    ),
    Theme(
        name = "Monochrome",
        colorScheme = "Mono Black",
        sidebar = "Pencil",
        terminal = "Spacegray",
        tabs = "Mono Black",
        active = "GitHub",
    ),
    Theme(
        name = "Arctic Aurora",
        colorScheme = "Nord",
        sidebar = "Material",
        terminal = "Ice",
        windows = "Nord",
        tabs = "Cobalt2",
        diff = "GitHub",
        fileBrowser = "Nord",
        active = "Aqua glow",
    ),
    Theme(
        name = "Sakura",
        colorScheme = "Rose Pine",
        sidebar = "Hopscotch",
        terminal = "Pastel Pink",
        windows = "Catppuccin",
        tabs = "Rose Pine",
        diff = "Catppuccin",
        fileBrowser = "Rose Pine",
        active = "Hot rose",
    ),
    Theme(
        name = "Copper Patina",
        colorScheme = "Material",
        sidebar = "Gruvbox",
        terminal = "Sea Foam",
        windows = "Material",
        tabs = "Sepia",
        diff = "Ayu Mirage",
        active = "Honey",
    ),
    Theme(
        name = "Midnight Violet",
        colorScheme = "Tokyo Night",
        sidebar = "Catppuccin",
        terminal = "Indigo",
        windows = "Tokyo Night",
        tabs = "Dracula",
        diff = "Rose Pine",
        active = "Royal violet",
    ),
    Theme(
        name = "Sandstorm",
        colorScheme = "Sepia",
        sidebar = "Gruvbox",
        terminal = "Sand",
        windows = "Sepia",
        tabs = "Monokai",
        diff = "Gruvbox",
        fileBrowser = "Sepia",
        active = "Apricot",
    ),
    Theme(
        name = "Electric Blue",
        colorScheme = "Cobalt2",
        sidebar = "Nord",
        terminal = "Cobalt",
        windows = "Cobalt2",
        tabs = "Night Owl",
        diff = "Material",
        active = "Periwinkle",
    ),
    Theme(
        name = "Jungle",
        colorScheme = "Ayu",
        sidebar = "Material",
        terminal = "Forest",
        windows = "Ayu",
        tabs = "Nord",
        diff = "Gruvbox",
        fileBrowser = "Ayu Mirage",
        active = "Teal Storm",
    ),
    Theme(
        name = "Campfire",
        colorScheme = "Gruvbox",
        sidebar = "Sepia",
        terminal = "Amber CRT",
        windows = "Monokai",
        tabs = "Gruvbox",
        diff = "One Dark",
        fileBrowser = "Gruvbox",
        active = "Sunset",
    ),
    Theme(
        name = "Frost",
        colorScheme = "GitHub",
        sidebar = "Nord",
        terminal = "Sky",
        windows = "GitHub",
        tabs = "Spacegray",
        diff = "Nord",
        active = "Periwinkle",
    ),
    Theme(
        name = "Twilight",
        colorScheme = "Ayu Mirage",
        sidebar = "Tokyo Night",
        terminal = "Lavender",
        windows = "Ayu Mirage",
        tabs = "Catppuccin",
        diff = "Dracula",
        active = "Synthwave",
    ),
    Theme(
        name = "Autumn Leaves",
        colorScheme = "Monokai",
        sidebar = "Gruvbox",
        terminal = "Amber Glow",
        windows = "Sepia",
        tabs = "Monokai",
        diff = "Gruvbox",
        fileBrowser = "Monokai",
        active = "Olive",
    ),
    Theme(
        name = "Coral Reef",
        colorScheme = "Night Owl",
        sidebar = "Material",
        terminal = "Sea Foam",
        windows = "Night Owl",
        tabs = "Cobalt2",
        diff = "Ayu Mirage",
        fileBrowser = "Night Owl",
        active = "Aqua glow",
    ),
    Theme(
        name = "Starlight",
        colorScheme = "One Dark",
        sidebar = "Catppuccin",
        terminal = "Nord",
        windows = "Spacegray",
        tabs = "One Dark",
        diff = "Tokyo Night",
        active = "Periwinkle",
    ),
    Theme(
        name = "Driftwood",
        colorScheme = "Sepia",
        sidebar = "Material",
        terminal = "Peach",
        windows = "Sepia",
        tabs = "Gruvbox",
        diff = "Monokai",
        fileBrowser = "Sepia",
        active = "Sand",
    ),
    Theme(
        name = "Nebula",
        colorScheme = "Catppuccin",
        sidebar = "Tokyo Night",
        terminal = "Royal violet",
        windows = "Catppuccin",
        tabs = "Dracula",
        diff = "Rose Pine",
        active = "Synthwave",
    ),
    Theme(
        name = "Evergreen",
        colorScheme = "Material",
        sidebar = "Nord",
        terminal = "Forest",
        windows = "Material",
        tabs = "Gruvbox",
        diff = "Ayu Mirage",
        fileBrowser = "Material",
        active = "Sea Foam",
    ),

    // ── Bold light-mode configurations ────────────────────────────────
    // Each pairs a pastel content theme with a medium-saturated "Panel"
    // sidebar/chrome and a vivid "Bar" tab strip so the UI never
    // collapses to white/yellow/grey. The panel tone is deliberately
    // mid-weight — clearly coloured, but not so dark it turns the light
    // mode into a near-dark mode. The bottomBar is pulled to the panel
    // hue so the chrome reads as a single coloured frame around the
    // soft content.

    Theme(
        name = "Midnight Library",
        mode = ConfigMode.Light,
        colorScheme = "Sepia",
        sidebar = "Midnight Panel",
        terminal = "Sepia",
        windows = "Sepia",
        tabs = "Tangerine Bar",
        chrome = "Midnight Panel",
        diff = "Sepia",
        fileBrowser = "Midnight Panel",
        active = "Tangerine Bar",
        bottomBar = "Midnight Panel",
    ),
    Theme(
        name = "Emerald Garden",
        mode = ConfigMode.Light,
        colorScheme = "Mint Chip",
        sidebar = "Forest Panel",
        terminal = "Mint Chip",
        windows = "Mint Chip",
        tabs = "Hot Magenta Bar",
        chrome = "Forest Panel",
        diff = "Mint Chip",
        fileBrowser = "Forest Panel",
        active = "Hot Magenta Bar",
        bottomBar = "Forest Panel",
    ),
    Theme(
        name = "Plum Velvet",
        mode = ConfigMode.Light,
        colorScheme = "Lavender Dream",
        sidebar = "Royal Plum Panel",
        terminal = "Lavender Dream",
        windows = "Lavender Dream",
        tabs = "Cyan Bar",
        chrome = "Royal Plum Panel",
        diff = "Lavender Dream",
        fileBrowser = "Royal Plum Panel",
        active = "Cyan Bar",
        bottomBar = "Royal Plum Panel",
    ),
    Theme(
        name = "Vintage Wine",
        mode = ConfigMode.Light,
        colorScheme = "Rose Quartz",
        sidebar = "Burgundy Panel",
        terminal = "Rose Quartz",
        windows = "Rose Quartz",
        tabs = "Tangerine Bar",
        chrome = "Burgundy Panel",
        diff = "Rose Quartz",
        fileBrowser = "Burgundy Panel",
        active = "Tangerine Bar",
        bottomBar = "Burgundy Panel",
    ),
    Theme(
        name = "Italian Espresso",
        mode = ConfigMode.Light,
        colorScheme = "Sepia",
        sidebar = "Espresso Panel",
        terminal = "Sepia",
        windows = "Sepia",
        tabs = "Tangerine Bar",
        chrome = "Espresso Panel",
        diff = "Sepia",
        fileBrowser = "Espresso Panel",
        active = "Tangerine Bar",
        bottomBar = "Espresso Panel",
    ),
    Theme(
        name = "Tropical Lagoon",
        mode = ConfigMode.Light,
        colorScheme = "Tidepool",
        sidebar = "Deep Teal Panel",
        terminal = "Tidepool",
        windows = "Tidepool",
        tabs = "Hot Magenta Bar",
        chrome = "Deep Teal Panel",
        diff = "Tidepool",
        fileBrowser = "Deep Teal Panel",
        active = "Hot Magenta Bar",
        bottomBar = "Deep Teal Panel",
    ),
    Theme(
        name = "Slate Office",
        mode = ConfigMode.Light,
        colorScheme = "Paper White",
        sidebar = "Slate Panel",
        terminal = "Paper White",
        windows = "Paper White",
        tabs = "Cyan Bar",
        chrome = "Slate Panel",
        diff = "Paper White",
        fileBrowser = "Slate Panel",
        active = "Cyan Bar",
        bottomBar = "Slate Panel",
    ),
    Theme(
        name = "Indigo Bloom",
        mode = ConfigMode.Light,
        colorScheme = "Lavender Dream",
        sidebar = "Indigo Panel",
        terminal = "Lavender Dream",
        windows = "Lavender Dream",
        tabs = "Hot Magenta Bar",
        chrome = "Indigo Panel",
        diff = "Lavender Dream",
        fileBrowser = "Indigo Panel",
        active = "Hot Magenta Bar",
        bottomBar = "Indigo Panel",
    ),
    Theme(
        name = "Terracotta Patio",
        mode = ConfigMode.Light,
        colorScheme = "Marigold",
        sidebar = "Terracotta Panel",
        terminal = "Marigold",
        windows = "Marigold",
        tabs = "Cyan Bar",
        chrome = "Terracotta Panel",
        diff = "Marigold",
        fileBrowser = "Terracotta Panel",
        active = "Cyan Bar",
        bottomBar = "Terracotta Panel",
    ),
    Theme(
        name = "Olive Grove",
        mode = ConfigMode.Light,
        colorScheme = "Citrus Zest",
        sidebar = "Olive Panel",
        terminal = "Citrus Zest",
        windows = "Citrus Zest",
        tabs = "Tangerine Bar",
        chrome = "Olive Panel",
        diff = "Citrus Zest",
        fileBrowser = "Olive Panel",
        active = "Tangerine Bar",
        bottomBar = "Olive Panel",
    ),
    Theme(
        name = "Cocoa & Cream",
        mode = ConfigMode.Light,
        colorScheme = "Peach Sorbet",
        sidebar = "Mocha Panel",
        terminal = "Peach Sorbet",
        windows = "Peach Sorbet",
        tabs = "Tangerine Bar",
        chrome = "Mocha Panel",
        diff = "Peach Sorbet",
        fileBrowser = "Mocha Panel",
        active = "Tangerine Bar",
        bottomBar = "Mocha Panel",
    ),
    Theme(
        name = "Charcoal Pearl",
        mode = ConfigMode.Light,
        colorScheme = "Paper White",
        sidebar = "Charcoal Panel",
        terminal = "Paper White",
        windows = "Paper White",
        tabs = "Cyan Bar",
        chrome = "Charcoal Panel",
        diff = "Paper White",
        fileBrowser = "Charcoal Panel",
        active = "Cyan Bar",
        bottomBar = "Charcoal Panel",
    ),
    Theme(
        name = "Beach Cabana",
        mode = ConfigMode.Light,
        colorScheme = "Sky Breeze",
        sidebar = "Deep Teal Panel",
        terminal = "Sky Breeze",
        windows = "Sky Breeze",
        tabs = "Tangerine Bar",
        chrome = "Deep Teal Panel",
        diff = "Sky Breeze",
        fileBrowser = "Deep Teal Panel",
        active = "Tangerine Bar",
        bottomBar = "Deep Teal Panel",
    ),
    Theme(
        name = "Berry Tart",
        mode = ConfigMode.Light,
        colorScheme = "Cotton Candy",
        sidebar = "Royal Plum Panel",
        terminal = "Cotton Candy",
        windows = "Cotton Candy",
        tabs = "Hot Magenta Bar",
        chrome = "Royal Plum Panel",
        diff = "Cotton Candy",
        fileBrowser = "Royal Plum Panel",
        active = "Hot Magenta Bar",
        bottomBar = "Royal Plum Panel",
    ),
    Theme(
        name = "Lemon Forest",
        mode = ConfigMode.Light,
        colorScheme = "Citrus Zest",
        sidebar = "Forest Panel",
        terminal = "Citrus Zest",
        windows = "Citrus Zest",
        tabs = "Tangerine Bar",
        chrome = "Forest Panel",
        diff = "Citrus Zest",
        fileBrowser = "Forest Panel",
        active = "Lime Bar",
        bottomBar = "Forest Panel",
    ),
    Theme(
        name = "Watermelon Picnic",
        mode = ConfigMode.Light,
        colorScheme = "Rose Quartz",
        sidebar = "Forest Panel",
        terminal = "Rose Quartz",
        windows = "Rose Quartz",
        tabs = "Hot Magenta Bar",
        chrome = "Forest Panel",
        diff = "Rose Quartz",
        fileBrowser = "Forest Panel",
        active = "Lime Bar",
        bottomBar = "Forest Panel",
    ),
    Theme(
        name = "Aurora Mist",
        mode = ConfigMode.Light,
        colorScheme = "Mint Chip",
        sidebar = "Indigo Panel",
        terminal = "Mint Chip",
        windows = "Mint Chip",
        tabs = "Cyan Bar",
        chrome = "Indigo Panel",
        diff = "Mint Chip",
        fileBrowser = "Indigo Panel",
        active = "Hot Magenta Bar",
        bottomBar = "Indigo Panel",
    ),
    Theme(
        name = "Sunset Diner",
        mode = ConfigMode.Light,
        colorScheme = "Coral Reef",
        sidebar = "Burgundy Panel",
        terminal = "Coral Reef",
        windows = "Coral Reef",
        tabs = "Tangerine Bar",
        chrome = "Burgundy Panel",
        diff = "Coral Reef",
        fileBrowser = "Burgundy Panel",
        active = "Tangerine Bar",
        bottomBar = "Burgundy Panel",
    ),
    Theme(
        name = "Pearl Diver",
        mode = ConfigMode.Light,
        colorScheme = "Tidepool",
        sidebar = "Midnight Panel",
        terminal = "Tidepool",
        windows = "Tidepool",
        tabs = "Cyan Bar",
        chrome = "Midnight Panel",
        diff = "Tidepool",
        fileBrowser = "Midnight Panel",
        active = "Cyan Bar",
        bottomBar = "Midnight Panel",
    ),
    // Slack-inspired: white content area, medium slate-blue sidebars,
    // deep navy tab/top bar — the signature Slack "navy" light look.
    // Marked Both so dark mode also gets a cohesive three-tier look
    // (darkest navy tabs → mid navy sidebar → dark navy content).
    Theme(
        name = "Slack",
        mode = ConfigMode.Both,
        colorScheme = "Slack Canvas",
        sidebar = "Slack Slate Panel",
        terminal = "Slack Canvas",
        windows = "Slack Slate Panel",
        tabs = "Slack Navy Panel",
        chrome = "Slack Navy Panel",
        diff = "Slack Canvas",
        fileBrowser = "Slack Slate Panel",
        active = "Slack Navy Panel",
        bottomBar = "Slack Navy Panel",
    ),
    Theme(
        name = "Confetti Party",
        mode = ConfigMode.Light,
        colorScheme = "Cotton Candy",
        sidebar = "Royal Plum Panel",
        terminal = "Cotton Candy",
        windows = "Cotton Candy",
        tabs = "Lime Bar",
        chrome = "Cyan Bar",
        diff = "Cotton Candy",
        fileBrowser = "Royal Plum Panel",
        active = "Hot Magenta Bar",
        bottomBar = "Cyan Bar",
    ),

    // ── Bold dark-mode configurations ─────────────────────────────────
    // Same recipe for dark mode: a saturated content theme paired with
    // a Panel sidebar and a vivid Bar tab strip so the dark UI is full
    // of colour rather than just black/grey.

    Theme(
        name = "Neon Carnival",
        mode = ConfigMode.Dark,
        colorScheme = "Catppuccin",
        sidebar = "Hot Magenta Bar",
        terminal = "Catppuccin",
        windows = "Catppuccin",
        tabs = "Cyan Bar",
        chrome = "Royal Plum Panel",
        diff = "Catppuccin",
        fileBrowser = "Royal Plum Panel",
        active = "Lime Bar",
        bottomBar = "Royal Plum Panel",
    ),
    Theme(
        name = "Deep Sea Trench",
        mode = ConfigMode.Dark,
        colorScheme = "Deep Sea",
        sidebar = "Midnight Panel",
        terminal = "Deep Sea",
        windows = "Deep Sea",
        tabs = "Cyan Bar",
        chrome = "Midnight Panel",
        diff = "Deep Sea",
        fileBrowser = "Midnight Panel",
        active = "Cyan Bar",
        bottomBar = "Midnight Panel",
    ),
    Theme(
        name = "Galactic Drift",
        mode = ConfigMode.Dark,
        colorScheme = "Nebula",
        sidebar = "Royal Plum Panel",
        terminal = "Nebula",
        windows = "Nebula",
        tabs = "Cyan Bar",
        chrome = "Royal Plum Panel",
        diff = "Nebula",
        fileBrowser = "Royal Plum Panel",
        active = "Hot Magenta Bar",
        bottomBar = "Royal Plum Panel",
    ),
    Theme(
        name = "Phoenix Rise",
        mode = ConfigMode.Dark,
        colorScheme = "Volcanic",
        sidebar = "Burgundy Panel",
        terminal = "Volcanic",
        windows = "Volcanic",
        tabs = "Tangerine Bar",
        chrome = "Burgundy Panel",
        diff = "Volcanic",
        fileBrowser = "Burgundy Panel",
        active = "Tangerine Bar",
        bottomBar = "Burgundy Panel",
    ),
    Theme(
        name = "Forest Spirit",
        mode = ConfigMode.Dark,
        colorScheme = "Aurora",
        sidebar = "Forest Panel",
        terminal = "Aurora",
        windows = "Aurora",
        tabs = "Lime Bar",
        chrome = "Forest Panel",
        diff = "Aurora",
        fileBrowser = "Forest Panel",
        active = "Lime Bar",
        bottomBar = "Forest Panel",
    ),
    Theme(
        name = "Royal Court",
        mode = ConfigMode.Dark,
        colorScheme = "Tokyo Night",
        sidebar = "Royal Plum Panel",
        terminal = "Tokyo Night",
        windows = "Tokyo Night",
        tabs = "Tangerine Bar",
        chrome = "Royal Plum Panel",
        diff = "Tokyo Night",
        fileBrowser = "Royal Plum Panel",
        active = "Tangerine Bar",
        bottomBar = "Royal Plum Panel",
    ),
    Theme(
        name = "Storm Front",
        mode = ConfigMode.Dark,
        colorScheme = "Night Owl",
        sidebar = "Slate Panel",
        terminal = "Night Owl",
        windows = "Night Owl",
        tabs = "Cyan Bar",
        chrome = "Slate Panel",
        diff = "Night Owl",
        fileBrowser = "Slate Panel",
        active = "Cyan Bar",
        bottomBar = "Slate Panel",
    ),
    Theme(
        name = "Volcanic Lab",
        mode = ConfigMode.Dark,
        colorScheme = "Blood Moon",
        sidebar = "Burgundy Panel",
        terminal = "Blood Moon",
        windows = "Blood Moon",
        tabs = "Lime Bar",
        chrome = "Burgundy Panel",
        diff = "Blood Moon",
        fileBrowser = "Burgundy Panel",
        active = "Lime Bar",
        bottomBar = "Burgundy Panel",
    ),
    Theme(
        name = "Northern Lights",
        mode = ConfigMode.Dark,
        colorScheme = "Aurora",
        sidebar = "Indigo Panel",
        terminal = "Aurora",
        windows = "Aurora",
        tabs = "Hot Magenta Bar",
        chrome = "Indigo Panel",
        diff = "Aurora",
        fileBrowser = "Indigo Panel",
        active = "Hot Magenta Bar",
        bottomBar = "Indigo Panel",
    ),
    Theme(
        name = "Burnished Copper",
        mode = ConfigMode.Dark,
        colorScheme = "Dragon's Hoard",
        sidebar = "Espresso Panel",
        terminal = "Dragon's Hoard",
        windows = "Dragon's Hoard",
        tabs = "Tangerine Bar",
        chrome = "Espresso Panel",
        diff = "Dragon's Hoard",
        fileBrowser = "Espresso Panel",
        active = "Tangerine Bar",
        bottomBar = "Espresso Panel",
    ),
)

/**
 * Set of default theme configuration names for quick membership checks.
 *
 * Used to prevent users from creating custom configurations with names
 * that collide with built-in presets, and to identify default entries
 * in the merged configuration list.
 *
 * @see defaultThemes
 */
val defaultThemeConfigNames: Set<String> = defaultThemes.map { it.name }.toSet()
