{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-compose/0.2.6/toolkit-compose-0.2.6.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-compose",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-compose-jvm-0.2.6.jar",
          "url": "toolkit-compose-jvm-0.2.6.jar",
          "size": 3488,
          "sha512": "998b2faa95d9b78860e83efb42b92fb27bf01da400cf74b9c355e99af84831436ee686f1dec935592c47cdcd18bb50c6db5c973ec446dfb6e332b908ed2bcb1e",
          "sha256": "62edf481af4b5309c2a90ae55f786a02451d10f9c267982100848c1ffda9e954",
          "sha1": "b3a5cdb47e6db1622d798fb8d4bba4c0b34d5f03",
          "md5": "d46339d4340af4ada99850630b3d0ecb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-compose-jvm-0.2.6.jar",
          "url": "toolkit-compose-jvm-0.2.6.jar",
          "size": 3488,
          "sha512": "998b2faa95d9b78860e83efb42b92fb27bf01da400cf74b9c355e99af84831436ee686f1dec935592c47cdcd18bb50c6db5c973ec446dfb6e332b908ed2bcb1e",
          "sha256": "62edf481af4b5309c2a90ae55f786a02451d10f9c267982100848c1ffda9e954",
          "sha1": "b3a5cdb47e6db1622d798fb8d4bba4c0b34d5f03",
          "md5": "d46339d4340af4ada99850630b3d0ecb"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "toolkit-compose-jvm-0.2.6-sources.jar",
          "url": "toolkit-compose-jvm-0.2.6-sources.jar",
          "size": 1937,
          "sha512": "cf56103c015d2af0dc2607e9da994b2b3accf6cc83524babc96e9588a795a0901f62dc09ef0ae99034147972f96702c8d1d60c2f93484a128b66d7527b38bcdf",
          "sha256": "85be6d7729fefe0355968e891b874eb6dc0a7d5911b38ad1de8bae3d107a4166",
          "sha1": "1654a08151cfa3fe736a1dbb235433c4c633aad6",
          "md5": "9347455dabc525fd38f6efc130c2b160"
        }
      ]
    }
  ]
}
