{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.1.0/toolkit-core-0.1.0.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-jvm-0.1.0.jar",
          "url": "toolkit-core-jvm-0.1.0.jar",
          "size": 73704,
          "sha512": "6fe98c40449eb1ccde6dd60171e3e6d29ac334fa093174b9deb9847fe6210fafbb473f134098f64ae9ac439fa4d0ec898af9430aa4711f12f50f661920fee879",
          "sha256": "c26bda33ddbd999676b11fb9a4905988eabbc9a35bb8e9737250dd592c644e89",
          "sha1": "242fdb18fb5bd8e02280dd4310476e7f72cf6119",
          "md5": "a19fa6d43bd72d7d155b2346f4d449ce"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-jvm-0.1.0.jar",
          "url": "toolkit-core-jvm-0.1.0.jar",
          "size": 73704,
          "sha512": "6fe98c40449eb1ccde6dd60171e3e6d29ac334fa093174b9deb9847fe6210fafbb473f134098f64ae9ac439fa4d0ec898af9430aa4711f12f50f661920fee879",
          "sha256": "c26bda33ddbd999676b11fb9a4905988eabbc9a35bb8e9737250dd592c644e89",
          "sha1": "242fdb18fb5bd8e02280dd4310476e7f72cf6119",
          "md5": "a19fa6d43bd72d7d155b2346f4d449ce"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "toolkit-core-jvm-0.1.0-sources.jar",
          "url": "toolkit-core-jvm-0.1.0-sources.jar",
          "size": 27718,
          "sha512": "393d07f500c222a1564564f379105891d957b967ab7db66cff458d4758066326cb677ae85b583767d6d2db35924189ec8c088a4eb6bd6ffce3d60509ca71ea27",
          "sha256": "38786ba9b7b4f5defc649a05b25722e8737f6347e9839d4a4b55cc69ecc1092a",
          "sha1": "8bf61f2753b88d31a3d6c5c5f4afa70abf63a569",
          "md5": "4d0610ef728f2109d28bf166622e5395"
        }
      ]
    }
  ]
}
