{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-compose/0.2.27/toolkit-compose-0.2.27.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-compose",
    "version": "0.2.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.27"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-compose-release.aar",
          "url": "toolkit-compose-android-0.2.27.aar",
          "size": 29920,
          "sha512": "091cb7d4aaf424f1ca937f63b85eff733ec17981442493c09e9c7ed18711fd322095fe4f272f1c2716225dde481c3f79bc6a18d2b4da59729a356d15c35c2e04",
          "sha256": "0b898b4aef7be11ebf491b270284b3f6764fd71453e8dd1f06a872b3a33cb69d",
          "sha1": "d62a08b75b7b7acdd4d76f8cf5b8aebe3552349d",
          "md5": "dbb48d18e17dc807c7cec1ad3888d328"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.27"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "toolkit-compose-release.aar",
          "url": "toolkit-compose-android-0.2.27.aar",
          "size": 29920,
          "sha512": "091cb7d4aaf424f1ca937f63b85eff733ec17981442493c09e9c7ed18711fd322095fe4f272f1c2716225dde481c3f79bc6a18d2b4da59729a356d15c35c2e04",
          "sha256": "0b898b4aef7be11ebf491b270284b3f6764fd71453e8dd1f06a872b3a33cb69d",
          "sha1": "d62a08b75b7b7acdd4d76f8cf5b8aebe3552349d",
          "md5": "dbb48d18e17dc807c7cec1ad3888d328"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "toolkit-compose-android-0.2.27-sources.jar",
          "url": "toolkit-compose-android-0.2.27-sources.jar",
          "size": 5669,
          "sha512": "d93db2949e9df9eab1bf563b596e18cafc4dfbd5baaeb35d9c987ad6136673bc4cac7a06173681185b28b036448941cfc7074aa7c238484ec292209af54cf8fb",
          "sha256": "63f3b5242c5e608956c9a8f96af68d23ed896148ef497db1cf54b18554204500",
          "sha1": "64273cc6434e071397d92128916ba7e00838dc61",
          "md5": "3d59fc60d49d0ec209e5599d22a3877f"
        }
      ]
    }
  ]
}
