{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-web/0.2.26/toolkit-web-0.2.26.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-web",
    "version": "0.2.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.26"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.26.klib",
          "url": "toolkit-web-js-0.2.26.klib",
          "size": 748190,
          "sha512": "8d427158ca662a4fb23cdc13292e5f527f99756893285c5e23c5061f5624882548d915cdc1e845911571c472d345ed4dc2c2d6441c1290fc1b23224be3dff00a",
          "sha256": "e9f46f4b1e3f07ee6eb398de611242d057964de33c47521bae7400342c5bc423",
          "sha1": "79789dd708ed5f031ddb22a7f5582e9007e5983d",
          "md5": "deae691e02b552fea32b9600e213710d"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.26"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.26.klib",
          "url": "toolkit-web-js-0.2.26.klib",
          "size": 748190,
          "sha512": "8d427158ca662a4fb23cdc13292e5f527f99756893285c5e23c5061f5624882548d915cdc1e845911571c472d345ed4dc2c2d6441c1290fc1b23224be3dff00a",
          "sha256": "e9f46f4b1e3f07ee6eb398de611242d057964de33c47521bae7400342c5bc423",
          "sha1": "79789dd708ed5f031ddb22a7f5582e9007e5983d",
          "md5": "deae691e02b552fea32b9600e213710d"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-web-js-0.2.26-sources.jar",
          "url": "toolkit-web-js-0.2.26-sources.jar",
          "size": 318034,
          "sha512": "68f55a60146d4a3193d060ea4a54c3959d48b4be3cb8fdc940d4cf9d2ab5a0e7fccfa27f3ae671fdbe1cd3b181166592149d5ef0491edff09b73483a76a4bcbd",
          "sha256": "dd8e3edc218660ad4ad33a727261cd1e9c767f45ecef01f90ea3ff7c508a3b42",
          "sha1": "776bf032f323d190aa94a926839d84626bb2189c",
          "md5": "9fca5de5d659a791ae2ddc1e972057bb"
        }
      ]
    }
  ]
}
