{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.26/toolkit-core-0.2.26.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-jvm-0.2.26.jar",
          "url": "toolkit-core-jvm-0.2.26.jar",
          "size": 90272,
          "sha512": "8d5077ca3305ed1fc39e292764e039b74ea114fb6973da122b60d4e5f3901b8cdac49b3b8fd53988e4515097b18114c7b906f7e620bbd43c496ddde6a065d3b5",
          "sha256": "36f2419dcd59f0ea93dbd0c44d9c091fa05d9e70a8a051c7bfc5db4eeb420d10",
          "sha1": "716875d1e73916b853a52aa98d635a79deb5d3be",
          "md5": "3f2ff5522e1a982805cdfd48ccfadce6"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-jvm-0.2.26.jar",
          "url": "toolkit-core-jvm-0.2.26.jar",
          "size": 90272,
          "sha512": "8d5077ca3305ed1fc39e292764e039b74ea114fb6973da122b60d4e5f3901b8cdac49b3b8fd53988e4515097b18114c7b906f7e620bbd43c496ddde6a065d3b5",
          "sha256": "36f2419dcd59f0ea93dbd0c44d9c091fa05d9e70a8a051c7bfc5db4eeb420d10",
          "sha1": "716875d1e73916b853a52aa98d635a79deb5d3be",
          "md5": "3f2ff5522e1a982805cdfd48ccfadce6"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "toolkit-core-jvm-0.2.26-sources.jar",
          "url": "toolkit-core-jvm-0.2.26-sources.jar",
          "size": 36897,
          "sha512": "01f1553a6a32caa884b5371782f5a1ef0afddf053ddf670b703e17e4e6f84e8d7962f059932627945ea105ced67e5b9a946991a6cb867c459e433ae2baeaaa20",
          "sha256": "f0b15c9b2a3718ecbd3f0abadf61f22d1d1b3710bb510fbda2e605a2937b4a1e",
          "sha1": "2f61961a7bac422ba455d989ebcd805e0ad01b62",
          "md5": "d172e3d1869c0b012354d5c05143ee1f"
        }
      ]
    }
  ]
}
