{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.2.19/toolkit-store-0.2.19.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-js-0.2.19.klib",
          "url": "toolkit-store-js-0.2.19.klib",
          "size": 40524,
          "sha512": "38f20bbb9056051f465b51c7280be02554356c54954647128ec607a24cb459cb86878e5586099d295e05071e25fc47ee8f0367dcce01fff45ac15d1b5bed32f6",
          "sha256": "d8b0e7a7e3459d63dc4c73da59a3209f0166d1b4726b8e7c47938c8bd04c7a73",
          "sha1": "5cd8ec99233e48cd7a7af0b187ecaa23ea7210fd",
          "md5": "d20c73a1c3c8db6587b62c7d2f904514"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-js-0.2.19.klib",
          "url": "toolkit-store-js-0.2.19.klib",
          "size": 40524,
          "sha512": "38f20bbb9056051f465b51c7280be02554356c54954647128ec607a24cb459cb86878e5586099d295e05071e25fc47ee8f0367dcce01fff45ac15d1b5bed32f6",
          "sha256": "d8b0e7a7e3459d63dc4c73da59a3209f0166d1b4726b8e7c47938c8bd04c7a73",
          "sha1": "5cd8ec99233e48cd7a7af0b187ecaa23ea7210fd",
          "md5": "d20c73a1c3c8db6587b62c7d2f904514"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-store-js-0.2.19-sources.jar",
          "url": "toolkit-store-js-0.2.19-sources.jar",
          "size": 13668,
          "sha512": "17721f9f570fcd6dcbffb2ea8787d8e0748acb5f4f40c3e5987b8c518a8bdf275e1791dfb11816f7960c60d8302469e5e3c7b2f438eedbc8dc2be98ed8936350",
          "sha256": "03fb39ec43618d4f9c995457546f2dcdc7af1a824dca8849ddb78fbeb246b1b2",
          "sha1": "a93114666a41980ecbb1073daf01080a235051b6",
          "md5": "2e21d7f57c0ec88f19c9125c21b3e85a"
        }
      ]
    }
  ]
}
