{
  "formatVersion": "1.1",
  "component": {
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-metadata-0.1.0.jar",
          "url": "toolkit-core-0.1.0.jar",
          "size": 7915,
          "sha512": "3b5e9780db657b0dc063c8e1b6765fb40ea451e2c29f7a9933b9a6b4ffd545cdc37e38f96fce588c51be72c781475977d775b89d94c5f5268ed61ec9a68fb213",
          "sha256": "6fa5a6c7afe68a2481c825148ae6f1ec6b9d2a88a61a37dd6a71082d20e058fb",
          "sha1": "af74be2ae407a47a2625787f4d8cafc58ed354ee",
          "md5": "094bdb27db8fbad9b8b6a9abc4c3f114"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "toolkit-core-kotlin-0.1.0-sources.jar",
          "url": "toolkit-core-0.1.0-sources.jar",
          "size": 27718,
          "sha512": "393d07f500c222a1564564f379105891d957b967ab7db66cff458d4758066326cb677ae85b583767d6d2db35924189ec8c088a4eb6bd6ffce3d60509ca71ea27",
          "sha256": "38786ba9b7b4f5defc649a05b25722e8737f6347e9839d4a4b55cc69ecc1092a",
          "sha1": "8bf61f2753b88d31a3d6c5c5f4afa70abf63a569",
          "md5": "4d0610ef728f2109d28bf166622e5395"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../toolkit-core-android/0.1.0/toolkit-core-android-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../toolkit-core-android/0.1.0/toolkit-core-android-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../toolkit-core-android/0.1.0/toolkit-core-android-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toolkit-core-iosarm64/0.1.0/toolkit-core-iosarm64-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toolkit-core-iosarm64/0.1.0/toolkit-core-iosarm64-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toolkit-core-iosarm64/0.1.0/toolkit-core-iosarm64-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toolkit-core-iossimulatorarm64/0.1.0/toolkit-core-iossimulatorarm64-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toolkit-core-iossimulatorarm64/0.1.0/toolkit-core-iossimulatorarm64-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../toolkit-core-iossimulatorarm64/0.1.0/toolkit-core-iossimulatorarm64-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../toolkit-core-js/0.1.0/toolkit-core-js-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-js",
        "version": "0.1.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../toolkit-core-js/0.1.0/toolkit-core-js-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-js",
        "version": "0.1.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../toolkit-core-js/0.1.0/toolkit-core-js-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-js",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../toolkit-core-jvm/0.1.0/toolkit-core-jvm-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-jvm",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../toolkit-core-jvm/0.1.0/toolkit-core-jvm-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-jvm",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../toolkit-core-jvm/0.1.0/toolkit-core-jvm-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-core-jvm",
        "version": "0.1.0"
      }
    }
  ]
}
