{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.2.19/toolkit-store-0.2.19.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-jvm-0.2.19.jar",
          "url": "toolkit-store-jvm-0.2.19.jar",
          "size": 43549,
          "sha512": "7375495d7d08c2fef57e3d64c807603841b797444c74b5c623a72f3e51d5f72379066eb21b2fb6c095da21d7df0f88686d6acb3d4e626b77bd80fb4555eb4be7",
          "sha256": "43fb83b20d47d826d6a8ae3cebba78af0aa11150d42a5e0ec25c7992d5fd319a",
          "sha1": "c8efc767803d4f3adb6800779b6644796b7f1b82",
          "md5": "302ac18e82bca816dc3aee740ddfb6ce"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-jvm-0.2.19.jar",
          "url": "toolkit-store-jvm-0.2.19.jar",
          "size": 43549,
          "sha512": "7375495d7d08c2fef57e3d64c807603841b797444c74b5c623a72f3e51d5f72379066eb21b2fb6c095da21d7df0f88686d6acb3d4e626b77bd80fb4555eb4be7",
          "sha256": "43fb83b20d47d826d6a8ae3cebba78af0aa11150d42a5e0ec25c7992d5fd319a",
          "sha1": "c8efc767803d4f3adb6800779b6644796b7f1b82",
          "md5": "302ac18e82bca816dc3aee740ddfb6ce"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "toolkit-store-jvm-0.2.19-sources.jar",
          "url": "toolkit-store-jvm-0.2.19-sources.jar",
          "size": 17954,
          "sha512": "dc1f5de17e55ddcbc9a40a141b90db5a93fff9e2b8e096ab7ac30a22c818889bff2617d0ec476844e2ca789c1152fefe8a8681a71ca2c9a0fb1889e71a7ed362",
          "sha256": "d8295ff20f189a6a883af670308aefae511b99e622ab062db744d97c3c091509",
          "sha1": "9fae2b2b1bd06d04666e06e3f8a87fdf230d5e20",
          "md5": "8cbc12283298d52ca927ceaa071fddc6"
        }
      ]
    }
  ]
}
