{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.19/toolkit-core-0.2.19.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-jvm-0.2.19.jar",
          "url": "toolkit-core-jvm-0.2.19.jar",
          "size": 89357,
          "sha512": "1e1a4cef7822f678cfe36c1ae8f485991144b1659f90711c06d4f59c92f78e4f000b88cb7b25126b5bc0cc26f37a199b781b3799eafeb533e50c21dc04dd9cf8",
          "sha256": "f2c4cfdae3604f145ec39f220d2d0f3c6b737d378d489b6c923c9572f615e1c0",
          "sha1": "9547dce49e3650d6be395cb44f47d0ce78cb7c0f",
          "md5": "f9142079f84902b3aa2b2a4489eee1f0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-jvm-0.2.19.jar",
          "url": "toolkit-core-jvm-0.2.19.jar",
          "size": 89357,
          "sha512": "1e1a4cef7822f678cfe36c1ae8f485991144b1659f90711c06d4f59c92f78e4f000b88cb7b25126b5bc0cc26f37a199b781b3799eafeb533e50c21dc04dd9cf8",
          "sha256": "f2c4cfdae3604f145ec39f220d2d0f3c6b737d378d489b6c923c9572f615e1c0",
          "sha1": "9547dce49e3650d6be395cb44f47d0ce78cb7c0f",
          "md5": "f9142079f84902b3aa2b2a4489eee1f0"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "toolkit-core-jvm-0.2.19-sources.jar",
          "url": "toolkit-core-jvm-0.2.19-sources.jar",
          "size": 36059,
          "sha512": "d49a2c50b6eae1c7695567ee1445f3bafa377ceb428cf2d3d439449233975d13652355dc533522f58e775aca80660c41b614f48df750f6e265108ef09299edba",
          "sha256": "c4b41f4cc0d92ff82cd0e18b6a8bf1f764b571a90209ae87efc870aed7c8d51d",
          "sha1": "2c939e18e294e625096665aeec7030f3afdf3d9a",
          "md5": "995a158411c76885d5751a848c00db71"
        }
      ]
    }
  ]
}
