{
  "formatVersion": "1.1",
  "component": {
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-compose",
    "version": "0.2.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.26"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-compose-metadata-0.2.26.jar",
          "url": "toolkit-compose-0.2.26.jar",
          "size": 762,
          "sha512": "6e9cf83233f838a52f0fde57e0061644b8118693dac1377750c9b465b6afb238fdd93e3eb70afebb14e0e708d8410e53bb083acb680e2ace0cfc1c45e1ad29b2",
          "sha256": "318be4b86b8be76a3ed8db53200f4807f3e440e204bb74e2fbb4772825940f43",
          "sha1": "48fc930f225af1239a8cc35a43530c58e180647b",
          "md5": "8f4d7f3f6749dfd226854428bccce65c"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "toolkit-compose-kotlin-0.2.26-sources.jar",
          "url": "toolkit-compose-0.2.26-sources.jar",
          "size": 5238,
          "sha512": "d4da4ed92db69c392e2e32cbe21ab2d882f667b33553129a4695489d255104814e8d054dc143db38792d7e41fa43ab09efdfffcbb324e8fb134a7afb79297954",
          "sha256": "e07f32c0cb95863ee4c1111a6a6d7b07c29b17de180b1dbd34bd8d7df1e76260",
          "sha1": "8d52ebfaf4738574f67d0f106a9a8c5aae5049dc",
          "md5": "0043615e43dc74c01b372a6190d96d5e"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../toolkit-compose-android/0.2.26/toolkit-compose-android-0.2.26.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-compose-android",
        "version": "0.2.26"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../toolkit-compose-android/0.2.26/toolkit-compose-android-0.2.26.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-compose-android",
        "version": "0.2.26"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../toolkit-compose-android/0.2.26/toolkit-compose-android-0.2.26.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-compose-android",
        "version": "0.2.26"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../toolkit-compose-jvm/0.2.26/toolkit-compose-jvm-0.2.26.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-compose-jvm",
        "version": "0.2.26"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../toolkit-compose-jvm/0.2.26/toolkit-compose-jvm-0.2.26.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-compose-jvm",
        "version": "0.2.26"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../toolkit-compose-jvm/0.2.26/toolkit-compose-jvm-0.2.26.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-compose-jvm",
        "version": "0.2.26"
      }
    }
  ]
}
