{
  "formatVersion": "1.1",
  "component": {
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-compose",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-compose-metadata-0.1.0.jar",
          "url": "toolkit-compose-0.1.0.jar",
          "size": 762,
          "sha512": "6e9cf83233f838a52f0fde57e0061644b8118693dac1377750c9b465b6afb238fdd93e3eb70afebb14e0e708d8410e53bb083acb680e2ace0cfc1c45e1ad29b2",
          "sha256": "318be4b86b8be76a3ed8db53200f4807f3e440e204bb74e2fbb4772825940f43",
          "sha1": "48fc930f225af1239a8cc35a43530c58e180647b",
          "md5": "8f4d7f3f6749dfd226854428bccce65c"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "toolkit-compose-kotlin-0.1.0-sources.jar",
          "url": "toolkit-compose-0.1.0-sources.jar",
          "size": 2313,
          "sha512": "06e772c0d983c76d6de3e66032b99229a9b390d9382844dc452fdea0a89316a747071ebf8db61dce33405611c68585dff10b21ccd86da58ba0d2028ba290be89",
          "sha256": "e089282ea93552720c29ce6e82106afe38ad2d222db7a9489badbd3f27148025",
          "sha1": "da44815e59859b96e0a8c2e84239b33edff9637f",
          "md5": "64d1c8bde9c407fea3d9438ef71e4242"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../toolkit-compose-android/0.1.0/toolkit-compose-android-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-compose-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../toolkit-compose-android/0.1.0/toolkit-compose-android-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-compose-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../toolkit-compose-android/0.1.0/toolkit-compose-android-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-compose-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../toolkit-compose-jvm/0.1.0/toolkit-compose-jvm-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-compose-jvm",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../toolkit-compose-jvm/0.1.0/toolkit-compose-jvm-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-compose-jvm",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../toolkit-compose-jvm/0.1.0/toolkit-compose-jvm-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-compose-jvm",
        "version": "0.1.0"
      }
    }
  ]
}
