{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.2.26/toolkit-store-0.2.26.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.2.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.26"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iosArm64Main-0.2.26.klib",
          "url": "toolkit-store-iosarm64-0.2.26.klib",
          "size": 61089,
          "sha512": "adab3865a2ad98e150db262c1200155c5d986c488dfd918140afbadd2edd759390eb5874effb8e93752703cf2fda3c9da806fa0c04f511b30720b26f62962312",
          "sha256": "af0a7312f23e6d23abef2f5cae9630f9c7558557f7d3dc6739b839113e53cd6f",
          "sha1": "d17c662a3fd6ba318bc7f4a0844b7d4a1424c671",
          "md5": "4de37e2d92f6048b1166efc6a128efec"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toolkit-store-iosarm64-0.2.26-sources.jar",
          "url": "toolkit-store-iosarm64-0.2.26-sources.jar",
          "size": 17779,
          "sha512": "e2f6d3ef4c2984fb2d537b8c3c1102a3044da7ff7ba2f2ed72193ca56671133374fb8b803c4e2a83d696a6c5c52ceafcc36c183203070399d132388e790c6645",
          "sha256": "b4dab38a27904aa897f56c2f8b2ccc7c2513fd6508b7101fa8f42b8689234256",
          "sha1": "dd2a80c36e2049e1d96ef2483d5131de4285c613",
          "md5": "3064e8bf869402ff092488e955d7d0c8"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.26"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iosarm64-0.2.26-metadata.jar",
          "url": "toolkit-store-iosarm64-0.2.26-metadata.jar",
          "size": 3865,
          "sha512": "3b0bf03ceddfaf3792bad6c0c31a216702f2b79a634b23a14444bf1dfcc7227d5a2b12766e9b589cd0657cd9af5c59323d5e5eb3df1fb3709d27f9b8177fc7c6",
          "sha256": "dd4332737cc3d3cf69754566af509862dc09f5786044d7d778af01efb939d602",
          "sha1": "aa937244f0dd22957df426a5e744710d4aa92892",
          "md5": "8e783412d3dbf6ac2fe9cd2c0b053109"
        }
      ]
    }
  ]
}
