{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.2.8/toolkit-store-0.2.8.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-jvm-0.2.8.jar",
          "url": "toolkit-store-jvm-0.2.8.jar",
          "size": 43448,
          "sha512": "652ee6c503c499237ffbb7eca2cf2681cd8ad8bc902f8fb723b91498b6adf0bc1a34869097ed5fc2978778f9b542e5ee6aaa506ba44b72d8dd9bdf5ee17b727d",
          "sha256": "4782adee853dc4ad8fd4b5e0e9056690abd35bd94e1a7de71158791908fdb30c",
          "sha1": "12a87711307828a6b8bbcfd13bbe6f6d23fec71b",
          "md5": "b4287d7f86b2796b47ca1c1a61548143"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-jvm-0.2.8.jar",
          "url": "toolkit-store-jvm-0.2.8.jar",
          "size": 43448,
          "sha512": "652ee6c503c499237ffbb7eca2cf2681cd8ad8bc902f8fb723b91498b6adf0bc1a34869097ed5fc2978778f9b542e5ee6aaa506ba44b72d8dd9bdf5ee17b727d",
          "sha256": "4782adee853dc4ad8fd4b5e0e9056690abd35bd94e1a7de71158791908fdb30c",
          "sha1": "12a87711307828a6b8bbcfd13bbe6f6d23fec71b",
          "md5": "b4287d7f86b2796b47ca1c1a61548143"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "toolkit-store-jvm-0.2.8-sources.jar",
          "url": "toolkit-store-jvm-0.2.8-sources.jar",
          "size": 17761,
          "sha512": "4d5eaf18122d7128609542d870713d99b6bf1196f0c235ea602428582260fad1e11a5494e1d55e68a974b8a0a4c45ca98e7b5dcb0a3f8799fb6ee6837754752b",
          "sha256": "cf8b9e99f05fd495eb20e82752f7106c4f84c0f8cc0df5d83de05bf2f78e849f",
          "sha1": "d1a04e147a01b4eaea73d6d509e3ea18f30c254f",
          "md5": "f44e6790262a7889e8c9fbec8ff040c1"
        }
      ]
    }
  ]
}
