{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.27/toolkit-core-0.2.27.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-iosArm64Main-0.2.27.klib",
          "url": "toolkit-core-iosarm64-0.2.27.klib",
          "size": 135136,
          "sha512": "7be9ebf363ed4137421be450ca64a8eec64d46dc59206a58916a181ff3c7488bd6780b3bdbb7105bb6765ab18461a6cb9be4a77b3ebdb3f6796e444aec95d517",
          "sha256": "218ca5aa260113df74b0ac3d0141de90db7d89491669c0eb58b50c4e2c1f605b",
          "sha1": "7ab1d69d58563b1d88f51152b27c541120697445",
          "md5": "2fdab2726126e92edde61ae9649d3408"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toolkit-core-iosarm64-0.2.27-sources.jar",
          "url": "toolkit-core-iosarm64-0.2.27-sources.jar",
          "size": 40964,
          "sha512": "edd6d6125428e84ea3d9390db830dbfd273b2593ef13c9a42548754d70396d22ba60dde5c5f02fdf9a6a85211a1dfc34d26645bee086dd5801ef2b39c8a8a245",
          "sha256": "e195e9708cee1acb8d587adde76d18a83964ca59d34661cdf94500f3b78deac4",
          "sha1": "f9d1686f606552d29df8bc4760e65b3d509ef618",
          "md5": "e8d762e5bdee65a42c8f57ce16acea3e"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-iosarm64-0.2.27-metadata.jar",
          "url": "toolkit-core-iosarm64-0.2.27-metadata.jar",
          "size": 261,
          "sha512": "69d047771b53dc07be8e0a280b9456a541915bb9228f11563f526ec52d9140537bf717c2b66c357377d48e4bb7f15e5c73622ed4fe8b9fe7f72e70eec0bc88ed",
          "sha256": "e10f8b9101faa60a4c9e8448a00da69d47fc2eec170d82f62848845c3e1af0cd",
          "sha1": "3db780c90f30b71957662b69d046284fae872a01",
          "md5": "f6212a6d42f3073c2487cc2bbb8e2088"
        }
      ]
    }
  ]
}
