{
  "formatVersion": "1.1",
  "component": {
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-web",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-metadata-0.1.0.jar",
          "url": "toolkit-web-0.1.0.jar",
          "size": 647,
          "sha512": "c1202faf5fb2108ab1f93db76a2c11711a6cd898d0da87a3dfb5ffff5b21586323742791a4c120c11c332118aac00a48a58eeae1cff73a5f9aaf9e8e821b414a",
          "sha256": "a883859a734bdfcfa5883eb12c580a53dd1d0b161e01a7157778fd2d5d5c9271",
          "sha1": "4a2b0530c6748a26507ba65dad6b356852a4267b",
          "md5": "0bbfd760d022a5d5e4e079e60d9df216"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "toolkit-web-kotlin-0.1.0-sources.jar",
          "url": "toolkit-web-0.1.0-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../toolkit-web-js/0.1.0/toolkit-web-js-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-web-js",
        "version": "0.1.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../toolkit-web-js/0.1.0/toolkit-web-js-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-web-js",
        "version": "0.1.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../toolkit-web-js/0.1.0/toolkit-web-js-0.1.0.module",
        "group": "se.soderbjorn.darkness",
        "module": "toolkit-web-js",
        "version": "0.1.0"
      }
    }
  ]
}
