{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.27/toolkit-core-0.2.27.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-iosSimulatorArm64Main-0.2.27.klib",
          "url": "toolkit-core-iossimulatorarm64-0.2.27.klib",
          "size": 135202,
          "sha512": "d02ca8976b922563a8c710a46422c86b843455feb9cefba98b8c5a87a869c105c1a7b7152116ff4d67be85959d8324f33e64964b382a2f5ac17f93d07fff136b",
          "sha256": "639094431d6e17eb793ee5a3c3023768f0449b43835b4a8c5eb5004cf771c3fb",
          "sha1": "7d228c9f428bc0bda6fb80d29fd3e2f0f6f1f334",
          "md5": "ffb3e58c28c3ddefff0bc9d8a5b0ce79"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toolkit-core-iossimulatorarm64-0.2.27-sources.jar",
          "url": "toolkit-core-iossimulatorarm64-0.2.27-sources.jar",
          "size": 40964,
          "sha512": "edd6d6125428e84ea3d9390db830dbfd273b2593ef13c9a42548754d70396d22ba60dde5c5f02fdf9a6a85211a1dfc34d26645bee086dd5801ef2b39c8a8a245",
          "sha256": "e195e9708cee1acb8d587adde76d18a83964ca59d34661cdf94500f3b78deac4",
          "sha1": "f9d1686f606552d29df8bc4760e65b3d509ef618",
          "md5": "e8d762e5bdee65a42c8f57ce16acea3e"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-iossimulatorarm64-0.2.27-metadata.jar",
          "url": "toolkit-core-iossimulatorarm64-0.2.27-metadata.jar",
          "size": 261,
          "sha512": "69d047771b53dc07be8e0a280b9456a541915bb9228f11563f526ec52d9140537bf717c2b66c357377d48e4bb7f15e5c73622ed4fe8b9fe7f72e70eec0bc88ed",
          "sha256": "e10f8b9101faa60a4c9e8448a00da69d47fc2eec170d82f62848845c3e1af0cd",
          "sha1": "3db780c90f30b71957662b69d046284fae872a01",
          "md5": "f6212a6d42f3073c2487cc2bbb8e2088"
        }
      ]
    }
  ]
}
