{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.13/toolkit-core-0.2.13.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-jvm-0.2.13.jar",
          "url": "toolkit-core-jvm-0.2.13.jar",
          "size": 86121,
          "sha512": "6a779b05c203cf065cca6991b6b759d06e48e9d9c92a59a6d827137a0d8596d65a503b87d087ce59550a81c6c3a848beedc5c607b8aee29b977eb91017e2ba7e",
          "sha256": "e1ca28e3069c120e1f7c85ad030e6e24dd574e3ae8abe13c70b73b747b8cb187",
          "sha1": "8115e623e9d8c0c5f4dfb067daa21f4b6b3a83d3",
          "md5": "a097f0a7bf8011875d4ecd6ab31dae78"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-jvm-0.2.13.jar",
          "url": "toolkit-core-jvm-0.2.13.jar",
          "size": 86121,
          "sha512": "6a779b05c203cf065cca6991b6b759d06e48e9d9c92a59a6d827137a0d8596d65a503b87d087ce59550a81c6c3a848beedc5c607b8aee29b977eb91017e2ba7e",
          "sha256": "e1ca28e3069c120e1f7c85ad030e6e24dd574e3ae8abe13c70b73b747b8cb187",
          "sha1": "8115e623e9d8c0c5f4dfb067daa21f4b6b3a83d3",
          "md5": "a097f0a7bf8011875d4ecd6ab31dae78"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "toolkit-core-jvm-0.2.13-sources.jar",
          "url": "toolkit-core-jvm-0.2.13-sources.jar",
          "size": 34884,
          "sha512": "0ddf8ffee689fca519e246196e7a2f9e14c01037c656ab4965d15c6ed3588d54641e667a9678890debbc80da5550f357cab4729ff47c4df725138c460b64f362",
          "sha256": "ccf6401b684f6bc5734844f8ad8e6a521006df2a7ab2e050cd9508e3f60e55b9",
          "sha1": "e009720d355bdd0f2340674e237883c74adc09a7",
          "md5": "05f25cec43d8483dd716e908d6f5da33"
        }
      ]
    }
  ]
}
