{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.2.19/toolkit-store-0.2.19.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.2.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iosSimulatorArm64Main-0.2.19.klib",
          "url": "toolkit-store-iossimulatorarm64-0.2.19.klib",
          "size": 44877,
          "sha512": "9158a6be5969d5979863fd856be09502e78fad11e76c261ca71273f8803684c4cb3c27f0dd7ea4c85027fb377695f3e198ebceecf9ac635e29914b25203fe1c6",
          "sha256": "16c72667f703a8311088b1fa37b15243ffb456bf4ec23c6a227fbcc99079a0a1",
          "sha1": "f4b6a223bd1d68809888f051a42a2796e4d26308",
          "md5": "6e54c5af32cd3b2903304597f4d03d28"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toolkit-store-iossimulatorarm64-0.2.19-sources.jar",
          "url": "toolkit-store-iossimulatorarm64-0.2.19-sources.jar",
          "size": 13757,
          "sha512": "787276d15fa9af841b1fa66b73895da3875289a6a037c7e408725edef7c3f80b49be1b569ec2943ca309347390c219c29b3103b47c68491eeae47ccb03499ced",
          "sha256": "cd806bfef522f3138bab592e1c385d662e3bc90dbc34423a40f17163776cee88",
          "sha1": "bbbfcef44773ae04d02753d4e48012260da71a78",
          "md5": "e37a51a7ee22ecb62ea45dcb1fb8caf9"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iossimulatorarm64-0.2.19-metadata.jar",
          "url": "toolkit-store-iossimulatorarm64-0.2.19-metadata.jar",
          "size": 3865,
          "sha512": "a66a8ea4188c3bca2659eec858f246e8635bcc979b1af73cef6cfdfc23cc643c440322fe3be0136ee2b458cecca2623aa22b4eabb8457d2dd9f68ee29054415d",
          "sha256": "8624d2ee957421ac95acf335767244db20f646ebdce3ec41fa2a71687103aa54",
          "sha1": "9920db4f6b903250d526e7f4215f09920fe4863a",
          "md5": "54e831954127f4ccae2b08b41fe5559f"
        }
      ]
    }
  ]
}
