{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-web/0.2.8/toolkit-web-0.2.8.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-web",
    "version": "0.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.8.klib",
          "url": "toolkit-web-js-0.2.8.klib",
          "size": 643315,
          "sha512": "ef3a8339b48b03643b3d2b48951d6f0edb7cabb91f0b4ffb32bb3e90649a7f09912e40fe825ba71afb6f543bd39a7d25c6e440d4fab64f8027c7d83637dd4b44",
          "sha256": "bc71bd1768b35c5b48495f8b376c3681f3302333611146da7f6b92497bd9bc22",
          "sha1": "a1d2ad80857509d3df9b3e1bb991cbd285e9c8b1",
          "md5": "3a3e1e2dea4790d0317e4be42ca9b657"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.8.klib",
          "url": "toolkit-web-js-0.2.8.klib",
          "size": 643315,
          "sha512": "ef3a8339b48b03643b3d2b48951d6f0edb7cabb91f0b4ffb32bb3e90649a7f09912e40fe825ba71afb6f543bd39a7d25c6e440d4fab64f8027c7d83637dd4b44",
          "sha256": "bc71bd1768b35c5b48495f8b376c3681f3302333611146da7f6b92497bd9bc22",
          "sha1": "a1d2ad80857509d3df9b3e1bb991cbd285e9c8b1",
          "md5": "3a3e1e2dea4790d0317e4be42ca9b657"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-web-js-0.2.8-sources.jar",
          "url": "toolkit-web-js-0.2.8-sources.jar",
          "size": 267634,
          "sha512": "1201b0f9d29a3eeac4ba80a121e169d1d252ee5dbb6df028f233154c644ae7ac8cba15841f82f53f55fc7b2a92e9fa8b251a5a4adc94bada2e2c3d3b4c9079b7",
          "sha256": "98db0e229e68e8496c7b6d02025849c09c56a5c4d27a383633652dd2accb2e37",
          "sha1": "2d8bc289f7d7c9ac4b76870dd408375ea75cf283",
          "md5": "c4fbfd45011dabf8a062ad6658cc20f6"
        }
      ]
    }
  ]
}
