{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.2.27/toolkit-store-0.2.27.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.2.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.27"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iosArm64Main-0.2.27.klib",
          "url": "toolkit-store-iosarm64-0.2.27.klib",
          "size": 61089,
          "sha512": "adab3865a2ad98e150db262c1200155c5d986c488dfd918140afbadd2edd759390eb5874effb8e93752703cf2fda3c9da806fa0c04f511b30720b26f62962312",
          "sha256": "af0a7312f23e6d23abef2f5cae9630f9c7558557f7d3dc6739b839113e53cd6f",
          "sha1": "d17c662a3fd6ba318bc7f4a0844b7d4a1424c671",
          "md5": "4de37e2d92f6048b1166efc6a128efec"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toolkit-store-iosarm64-0.2.27-sources.jar",
          "url": "toolkit-store-iosarm64-0.2.27-sources.jar",
          "size": 17779,
          "sha512": "e2f6d3ef4c2984fb2d537b8c3c1102a3044da7ff7ba2f2ed72193ca56671133374fb8b803c4e2a83d696a6c5c52ceafcc36c183203070399d132388e790c6645",
          "sha256": "b4dab38a27904aa897f56c2f8b2ccc7c2513fd6508b7101fa8f42b8689234256",
          "sha1": "dd2a80c36e2049e1d96ef2483d5131de4285c613",
          "md5": "3064e8bf869402ff092488e955d7d0c8"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.27"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iosarm64-0.2.27-metadata.jar",
          "url": "toolkit-store-iosarm64-0.2.27-metadata.jar",
          "size": 3865,
          "sha512": "c2bb26cc967ce14f45f937c6a88cfcf1a1063f3cac45a97508d1c81b76e793ab2c2cdd41bb0caade90b6cb029e3248e350bb828d14722b8f9499e6b0ab35e83a",
          "sha256": "39a2c488a420968cdde434f3cf5be688ea36845a0a07578de425e92ec748da25",
          "sha1": "723a54f74d3c806d4bdec633325f54b6a48c105f",
          "md5": "050744c497c5f67a71b3a79919887202"
        }
      ]
    }
  ]
}
